variables:
  COMPILER: clang
  CCACHE_DIR: $(Pipeline.Workspace)/ccache

trigger:
- fix-this-bs

pool:
  vmImage: 'ubuntu-latest'

- task: CacheBeta@0
  inputs:
    key: ccache | $(Agent.OS)
    path: $(CCACHE_DIR)
  displayName: ccache

- bash: |
    docker pull rpcs3/rpcs3-travis-xenial:1.2
    docker run                      \
      -v $(pwd):/rpcs3              \
      --env-file .travis/travis.env \
      -v $CCACHE_DIR:/root/.ccache  \
      rpcs3/rpcs3-travis-xenial:1.2 \
      /bin/bash -ex /rpcs3/.travis/build-linux.bash
  displayName: Fetch and build with Docker

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'build/bin/rpcs3'
    TargetFolder: '$(Pipeline.Workspace)/artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Pipeline.Workspace)/artifacts'
    artifactName: drop
